fullname: Abel - Ruffini Theorem as a Mathematical Component
shortname: abel
organization: math-comp
opam_name: coq-mathcomp-abel
community: false
action: true
coqdoc: false

synopsis: >-
  Abel - Ruffini's theorem
description: |-
  This repository contains a proof of Abel - Galois Theorem
  (equivalence between being solvable by radicals and having a
  solvable Galois group) and Abel - Ruffini Theorem (unsolvability of
  quintic equations) in the Coq proof-assistant and using the
  Mathematical Components library.

authors:
- name : Sophie Bernard
  initial: true
- name: Cyril Cohen
  initial: true
- name: Assia Mahboubi
  initial: true
- name: Pierre-Yves Strub
  initial: true

publications:
- pub_url: https://hal.inria.fr/hal-03136002
  pub_title: >
    Unsolvability of the Quintic Formalized in
    Dependent Type Theory

opam-file-maintainer: Cyril Cohen <cyril.cohen@inria.fr>

opam-file-version: dev

license:
  fullname: CeCILL-B
  identifier: CECILL-B
  file: CeCILL-B

supported_coq_versions:
  text: Coq 8.18 to 9.0
  opam: '{ (>= "8.18" & < "9.1~") | = "dev" }'

tested_coq_opam_versions:
- version: 'coq-8.20'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.19'
  repo: 'mathcomp/mathcomp-dev'
- version: '2.2.0-coq-8.20'
  repo: 'mathcomp/mathcomp'
- version: '2.2.0-coq-8.19'
  repo: 'mathcomp/mathcomp'
- version: '2.1.0-coq-8.18'
  repo: 'mathcomp/mathcomp'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{ (>= "2.0.0" & < "2.3~") | = "dev" }'
  description: |-
    [MathComp ssreflect 2.0 and later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-fingroup
  description: |-
    [MathComp fingroup](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-algebra
  description: |-
    [MathComp algebra](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-solvable
  description: |-
    [MathComp solvable](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-field
  description: |-
    [MathComp field](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-real-closed
    version: '{ (>= "2.0.0") | = "dev" }'
  description: |-
    [MathComp real closed >= 2.0.0](https://github.com/math-comp/real-closed)
namespace: Abel

keywords:
- name: algebra
- name: Galois
- name: Abel Ruffini
- name: unsolvability of quintincs


documentation: |-
  ## Organization of the code

  - `abel.v` itself contains the main theorems:
    + `galois_solvable_by_radical` (requires explicit roots of unity),
    + `ext_solvable_by_radical` (equivalent, and still requires roots of unity),
    + `radical_solvable_ext` (no mention of roots of unity),
    + `AbelGalois`, (equivalence obtained from the above two, requires
    roots of unity), and consequences on solvability of polynomial
    + and their consequence on the example polynomial X⁵ -4X + 2:
    `example_not_solvable_by_radicals`,

  - `xmathcomp/various.v` contains various (rather straightforward)
    extensions that should be added to various mathcomp packages asap
    with potential minor modifications,

  - `xmathcomp/char0.v` contains 0 characteristic specific results,
    that could use a refactoring for a smoother integration with
    mathcomp. e.g. ratr could get a canonical structure or rmorphism
    when the target field is a `lmodType ratr`, and we could provide a
    wrapper`NullCharType` akin to `PrimeCharType` (from `finfield.v`),

  - `xmathcomp/cyclotomic.v` contains complementary results about
    cyclotomic polynomials,

  - `xmathcomp/map_gal.v` contains complementary results about galois
    groups and galois extensions, including various isomorphisms,
    minimal galois extensions, solvable extensions, and mapping galois
    groups and galois extensions from a splitting field to
    another. This last construction is essential in switching to
    fields with roots of unity when we do not have them yet,

  - `xmathcomp/classic_ext.v` contains the theory of classic
    extensions by arbitrary polynomials, most of the results there are
    in the classically monad, making the results available either for
    a boolean goal or a classical goal. This was instrumental in
    eliminating references to some embarrassing roots of the unity.

  - `xmathcomp/algR.v` contains a proof that the real subset of `algC`
    (isomorphic to `{x : algC | x \is Num.real}`) is a real closed field
    (and archimedean), and endows this type `algR` with appropriate
    canonical instances.

  - `xmathcomp/real_closed_ext.v` contains some missing lemmas from
    the library `math-comp/real_closed`, in particular bounding the
    number of real roots of a polynomial by one plus the number of
    real roots of its derivative,

  ## Development information

  [Developping with nix](NIX.md)
